version: "3.8"

services:
  laravel-app:
    build: ./laravel
    container_name: laravel-app
    volumes:
      - ./laravel:/var/www/html
    depends_on:
      - mysql

  laravel-nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    ports:
      - "8080:80"
    volumes:
      - ./laravel:/var/www/html
      - ./laravel/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel-app

  react-app:
    build: ./react
    container_name: react-app
    ports:
      - "3000:80"
    stdin_open: true
    tty: true

  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
